[package]
name = "UnnatOS"
version = "0.1.0"
edition = "2021"

[dependencies]
indextree = "4.7.3"
mlua = { version = "0.10.3", features = ["lua54"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
